version: "3.9"

services:
  db:
    image: postgres:15.1
    env_file:
      .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis


  web:
    build: .
    image: nov-11-web
    depends_on:
      - db
      - redis
    volumes:
      - .:/src
      - static:/static
    env_file:
      - .env

    command: /bin/bash -c  "pip install -r requirements.txt &&  invoke runit"

  bot:
    build: .
    image: nov-11-web
    depends_on:
      - db
      - redis
    volumes:
      - .:/src
      - static:/static
    env_file:
      - .env

    command: /bin/bash -c  "pip install -r requirements.txt && ./manage.py run_bot"

  client:
    image: node:16.14.2
    volumes:
      - ./client:/src
    command: /bin/bash -c "cd /src/; npm i; npm run dev"
    ports:
      - 3000:3000

  celery-worker:
    build: .
    image: nov-11-web
    depends_on:
      - db
      - redis
    volumes:
      - .:/src
      - static:/static
    env_file:
      - .env
    command: /bin/bash -c  "pip install -r requirements.txt &&  celery -A config.celery worker -l INFO"

  celery-beat:
    build: .
    image: nov-11-web
    depends_on:
      - db
      - redis
    volumes:
      - .:/src
      - static:/static
    env_file:
      - .env
    command: /bin/bash -c  "pip install -r requirements.txt &&  celery -A config.celery beat  -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"


  nginx:
    image: nginx:1.23.3
    networks:
      - default
      - nginx-proxy
    volumes:
      - static:/static:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
      - client
    ports:
      - "8000:80"
    environment:
      - VIRTUAL_HOST=nov-11.ogir-ok.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=nov-11.ogir-ok.com
      - LETSENCRYPT_EMAIL=admin@nov-11.ogir-ok.com


networks:
  default:
  nginx-proxy:
    name: nginx-proxy

volumes:
  pgdata:
  static: