version: 2.1

# Define the jobs we want to run for this project
jobs:
  prospector:
    docker:
      - image: ogirok/nov-11-deploy
    steps:
      - checkout
      - restore_cache:
          key: python-dev-requirements
      - run: pip install -r requirements-dev.txt
      - save_cache:
          key: python-dev-requirements-3.9
          paths:
            - /usr/local/lib/python3.9/site-packages
      - run: prospector apps

  tests:
    docker:
      - image: ogirok/nov-11-deploy
    steps:
      - checkout
      - restore_cache:
          key: python-dev-requirements
      - run: pip install -r requirements-dev.txt
      - save_cache:
          key: python-dev-requirements-3.9
          paths:
            - /usr/local/lib/python3.9/site-packages
      - run: coverage run ./manage.py test
      - run: coverage report --fail-under=80

  deploy_dev:
    docker:
      - image: ogirok/nov-11-deploy
    steps:
      - checkout
      - run: pip install boto3
      - run: python deploy.py


# Orchestrate our job run sequence
workflows:
  check_and_deploy:
    jobs:
      - prospector
      - tests
      - deploy_dev:
          requires: ['prospector', 'tests']
          filters:
            branches:
              only:
                - main
