# Generated by Django 4.0.6 on 2023-01-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(null=True, verbose_name='Year'),
        ),
    ]
