# Generated by Django 4.0.6 on 2023-01-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_alter_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title_type',
            field=models.CharField(choices=[('short', 'Short Movie'), ('movie', 'Movie')], max_length=80, verbose_name='Type of the Movie'),
        ),
    ]
