# Generated by Django 4.0.6 on 2023-01-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0003_alter_movie_title_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personmovie',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='personmovie',
            old_name='person_id',
            new_name='person',
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.DateField(null=True, verbose_name='Birth Year'),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_year',
            field=models.DateField(null=True, verbose_name='Death Year'),
        ),
    ]
