# Generated by Django 4.0.6 on 2023-01-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0005_alter_personmovie_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmovie',
            name='category',
            field=models.CharField(max_length=120, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='personmovie',
            name='job',
            field=models.CharField(max_length=120, null=True, verbose_name='Job'),
        ),
    ]
