# Generated by Django 4.0.6 on 2023-01-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='used_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
